// prisma/seed/block-connections.consts.ts
import { RelationshipMetadataKey } from '../../generated/client';

/**
 * Interface for a single metadata entry within a block relationship.
 */
interface BlockRelationshipMetadata {
  id: string; // Hardcoded UUID for the metadata entry
  key: RelationshipMetadataKey;
  value: string;
}

/**
 * Interface for defining a block connection.
 */
export interface BlockConnectionData {
  id: string; // Hardcoded UUID for the BlockRelationship
  prerequisiteBlockId: string; // Block ID of the prerequisite course/module
  postrequisiteBlockId: string; // Block ID of the postrequisite course/module
  metadata?: BlockRelationshipMetadata[]; // Optional metadata for the relationship
}

/**
 * Array of block connections to be seeded.
 *
 * IMPORTANT: Replace placeholder UUIDs with actual hardcoded UUIDs generated by `uuidgen`.
 * Ensure the `prerequisiteBlockId` and `postrequisiteBlockId` correspond to the `blockId`
 * of your seeded courses or modules.
 */
export const BLOCK_CONNECTIONS: BlockConnectionData[] = [
  {
    id: 'D2EE6EFD-2892-4BA0-AF12-A9320B590C34',
    prerequisiteBlockId: '993a6a59-7fc7-4d96-ada6-5858d742496a', // Placeholder: Block ID for 'Linear Algebra 1'
    postrequisiteBlockId: '86fa4bd9-56ab-411b-8494-19124458b4dd', // Placeholder: Block ID for 'Linear Algebra 2'
    metadata: [
      {
        id: '1F56C39C-D614-4EE8-B283-F5812C9ADE3A',
        key: RelationshipMetadataKey.REASON,
        value: 'Foundational knowledge in linear algebra is required.',
      },
      {
        id: '7B5302AC-BDBC-4B36-AF08-AE191A7CEBD7',
        key: RelationshipMetadataKey.TYPE,
        value: 'hard', // Indicates a strict prerequisite
      },
    ],
  },
  // Add more block connections here as needed
  // {
  //   id: 'another-relationship-uuid',
  //   prerequisiteBlockId: 'block-id-of-course-x',
  //   postrequisiteBlockId: 'block-id-of-course-y',
  //   metadata: [
  //     { id: 'metadata-uuid-1', key: RelationshipMetadataKey.DESCRIPTION, value: 'Optional background' },
  //   ],
  // },
  {
    id: 'eced1d98-9bab-44af-84a4-cf788d704f6d',
    prerequisiteBlockId: 'a2f66714-72c3-4506-ab08-4da8b74809cf', // Block ID for 'Infinitesimal Calculus 1'
    postrequisiteBlockId: 'ac9e3b41-b2f5-4b77-8c76-1ef2293ea1f1', // Block ID for 'Infinitesimal Calculus 2'
    metadata: [
      {
        id: '4a0b90ed-1646-4677-bdcf-e85273c2c3c0',
        key: RelationshipMetadataKey.REASON,
        value:
          'Infinitesimal Calculus 1 is a prerequisite for Infinitesimal Calculus 2.',
      },
      {
        id: '5145788d-285a-4a51-82cb-61cbccdf0a25',
        key: RelationshipMetadataKey.TYPE,
        value: 'hard',
      },
    ],
  },
  {
    id: '76DC9C77-F975-4413-A3FF-CDF3F05B3518',
    prerequisiteBlockId: '19cfbc30-475c-4733-a5de-1064fa7f2ee7', // Block ID for 'Introduction to Computer Science and Java'
    postrequisiteBlockId: 'a6b8af63-5f91-4381-8a43-12f67d9ec34d', // Block ID for 'Data Structures and Introduction to Algorithms'
    metadata: [
      {
        id: '48671D00-0470-4B13-8A9F-96E95D27DE2E',
        key: RelationshipMetadataKey.REASON,
        value:
          'Introduction to Computer Science and Java is a prerequisite for Data Structures and Introduction to Algorithms.',
      },
      {
        id: 'F2416C88-D388-4CAF-8952-6049351A0C09',
        key: RelationshipMetadataKey.TYPE,
        value: 'hard',
      },
    ],
  },
  {
    id: 'A3B4C5D6-E7F8-9012-3456-789ABCDEF012',
    prerequisiteBlockId: '93063920-88DB-41DB-AFDD-1FDE26CA5686', // Block ID for 'Foundations of Mathematics'
    postrequisiteBlockId: '7b4f3a21-89d5-4c3e-a8f7-1e3d2c9b8a5f', // Block ID for 'Discrete Mathematics'
    metadata: [
      {
        id: '922D0EDA-AAFD-4E68-94CB-8C40B17714F4',
        key: RelationshipMetadataKey.REASON,
        value:
          'Foundations of Mathematics is a prerequisite for Discrete Mathematics.',
      },
      {
        id: '32474139-6904-4D6B-A0D1-171D45B2D472',
        key: RelationshipMetadataKey.TYPE,
        value: 'hard',
      },
    ],
  },
];
